--Create table for covid death 
CREATE TABLE covid_death (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    population BIGINT,
    total_cases BIGINT,
    new_cases BIGINT,
    new_cases_smoothed DECIMAL(10,2),
    total_deaths BIGINT,
    new_deaths BIGINT,
    new_deaths_smoothed DECIMAL(10,2),
    total_cases_per_million DECIMAL(10, 2),
    new_cases_per_million DECIMAL(10, 2),
    new_cases_smoothed_per_million DECIMAL(10, 2),
    total_deaths_per_million DECIMAL(10, 2),
    new_deaths_per_million DECIMAL(10, 2),
    new_deaths_smoothed_per_million DECIMAL(10, 2),
    reproduction_rate DECIMAL(5, 2),
    icu_patients BIGINT,
    icu_patients_per_million DECIMAL(10, 2),
    hosp_patients BIGINT,
    hosp_patients_per_million DECIMAL(10, 2),
    weekly_icu_admissions DECIMAL(10, 2),
    weekly_icu_admissions_per_million DECIMAL(10, 2),
    weekly_hosp_admissions DECIMAL(10,2),
    weekly_hosp_admissions_per_million DECIMAL(10, 2)
);

--Create table for Covid Vaccination
CREATE TABLE covid_vaccinations (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    new_tests BIGINT,
    total_tests BIGINT,
    total_tests_per_thousand DECIMAL(10, 2),
    new_tests_per_thousand DECIMAL(10, 2),
    new_tests_smoothed BIGINT,
    new_tests_smoothed_per_thousand DECIMAL(10, 2),
    positive_rate DECIMAL(5, 2),
    tests_per_case DECIMAL(10, 2),
    tests_units VARCHAR(50),
    total_vaccinations BIGINT,
    people_vaccinated BIGINT,
    people_fully_vaccinated BIGINT,
    new_vaccinations BIGINT,
    new_vaccinations_smoothed BIGINT,
    total_vaccinations_per_hundred DECIMAL(10, 2),
    people_vaccinated_per_hundred DECIMAL(10, 2),
    people_fully_vaccinated_per_hundred DECIMAL(10, 2),
    new_vaccinations_smoothed_per_million DECIMAL(10, 2),
    stringency_index DECIMAL(5, 2),
    population_density DECIMAL(10, 2),
    median_age DECIMAL(5, 2),
    aged_65_older DECIMAL(5, 2),
    aged_70_older DECIMAL(5, 2),
    gdp_per_capita DECIMAL(15, 2),
    extreme_poverty DECIMAL(5, 2),
    cardiovasc_death_rate DECIMAL(5, 2),
    diabetes_prevalence DECIMAL(5, 2),
    female_smokers DECIMAL(5, 2),
    male_smokers DECIMAL(5, 2),
    handwashing_facilities DECIMAL(5, 2),
    hospital_beds_per_thousand DECIMAL(5, 2),
    life_expectancy DECIMAL(5, 2),
    human_development_index DECIMAL(5, 2)
);

